account/urls.py
from django.urls import path

from account import views

app_name = "accounts"


urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("signin/", views.SignInView.as_view(), name="signin"),
    path("signout/", views.signout, name="signout"),
]

to_do_list/urls.py
from django.urls import path, include


from . views import CustomLoginView , TaskList,TaskDetail,TaskCreate,TaskUpdate,DeleteView,RegisterPage
from django.contrib.auth.views import LogoutView
from . import views
from django.urls import reverse
from django.conf.urls.static import static


app_name = 'to_do_list'



urlpatterns = [
    path('', views.index, name='index'),
    path('signin/', CustomLoginView.as_view(),name='signin'),
    path('tasks/',TaskList.as_view(),name='tasks'),
    path('logout/', LogoutView.as_view (next_page='to_do_list:signin'),name='logout'),
    path('profile/', views.profile, name='profile'),
    path('signup/',RegisterPage.as_view(), name='signup'),
    path('task/<int:pk>/',TaskDetail.as_view(),name='task'),
    path('create-task/',TaskCreate.as_view(),name='task-create'),
    path('task-update/<int:pk>/',TaskUpdate.as_view(),name='task-update'),
    path('task-delete/<int:pk>/',DeleteView.as_view(),name='task-delete'),   
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo_master/urls.py
from django.contrib import admin
from django.urls import path,include

from .views import DashboardView


# 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('to_do_list.urls')),
    path("", include("calendarapp.urls")),
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
]

to_do_list/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from celery import shared_task
from django.core.mail import send_mail



# Create your models here.
class Task(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    title=models.CharField(max_length=200)
    description=models.CharField(null=True,blank=True,max_length=200)
    complete = models.BooleanField(default=False)
    due  = models.DateTimeField(auto_now_add=False,auto_now=False,blank=True,null=True)
    time=models.TimeField( auto_now_add=False,auto_now=False,blank=True,null=True)
    
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering =['complete']
    
    
class Reminder(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    reminder_date = models.DateTimeField()

    def __str__(self):
        return f'Reminder for {self.task.title} at {self.reminder_date}'

to_do_list/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	# def save(self, commit=True):
	# 	user = super(NewUserForm, self).save(commit=False)
	# 	user.email = self.cleaned_data['email']
	# 	if commit:
	# 		user.save()
	# 	return user

account/views/signin.py
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login

from accounts.forms import SignInForm


class SignInView(View):
    """ User registration view """

    template_name = "accounts/signin.html"
    form_class = SignInForm

    def get(self, request, *args, **kwargs):
        forms = self.form_class()
        context = {"form": forms}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        forms = self.form_class(request.POST)
        if forms.is_valid():
            email = forms.cleaned_data["email"]
            password = forms.cleaned_data["password"]
            user = authenticate(email=email, password=password)
            if user:
                login(request, user)
                return redirect("calendarapp:calendar")
        context = {"form": forms}
        return render(request, self.template_name, context)

to_do_list/views.py
from django.shortcuts import render, redirect
from .models import Task
from django.views.generic.list import ListView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import NewUserForm
from django.contrib.auth import authenticate, login
from to_do_list.tasks import send_notification

def index(request):
    return render(request, 'landing/index.html')


def profile(request):
    return render(request, 'profile2.html')

class CustomLoginView(LoginView):
    template_name = 'to_do_list/signin.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('dashboard')
    






class TaskList(LoginRequiredMixin, ListView):
    models = Task
    queryset = models.objects.all()
    context_object_name = 'tasks'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tasks'] = context['tasks'].filter(user=self.request.user)
        context['count'] = context['tasks'].filter(complete=False).count()
        search_input = self.request.GET.get('search-area') or ''
        if search_input:
            context['tasks'] = context['tasks'].filter(title__icontains=search_input)

        context['search_input'] = search_input  
        return context 

class TaskDetail(LoginRequiredMixin, DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'to_do_list/task.html'

class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['title', 'description', 'complete', 'due', 'time']
    success_url = reverse_lazy('to_do_list:tasks')
      
    def form_valid(self, form):
        form.instance.user = self.request.user
        response = super(TaskCreate, self).form_valid(form)
        # send_notification.delay()
        return response

class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description', 'complete', 'due', 'time']
    success_url = reverse_lazy('to_do_list:tasks')

class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = 'task'
    success_url = reverse_lazy('to_do_list:tasks')

class RegisterPage(FormView):
    template_name = 'to_do_list/signup2.html'
    form_class = NewUserForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('dashboard')
    
    def form_valid(self, form):
        user = form.save()
        if user is not None:
           login(self.request,user)
        return super(RegisterPage,self).form_valid(form)
    
    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            
            return redirect('dashboard')
        return super(RegisterPage,self).get(*args,**kwargs)

to_do_list/templates/to_do_list/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>ToDo</title>
    <link rel="stylesheet" href="{% static 'todo/assets/bootstrap/css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins&amp;display=swap">
    <link rel="stylesheet" href="{% static 'todo/assets/fonts/fontawesome-all.min.css'%}">
    <link rel="stylesheet" href="{% static 'todo/assets/css/Login-Form-Basic-icons.css'%}">
    <link rel="stylesheet" href="{% static 'todo/assets/css/untitled.css'%}">
    <link rel="stylesheet" href="{% static 'css/accounts.css' %}" />
</head>

<body style="max-width: 100vw;max-height: 100vh;height: 100vh;overflow: hidden;overflow-y: hidden;">
    <section style="width: 100%;height: 100%;padding: 0px;" class="signup">
        <div class="row" style="width: 100%;height: 100%;background: white;margin: 0px;">
            <div class="col-md-6 col-sm-12" style="padding: 40px;background: #47126B;width: 50%;height: 100%;">
                <div style="background: white;width: auto;height: auto;padding: 6px;text-align: center;display: inline-block;"><i class="fas fa-user-lock" style="width: 100%;font-size: 28px;"></i></div>
                <h1 style="color: white;font-size: 22px;font-family: Poppins, sans-serif;margin-top: 30px;width: 80%;">Get more done with ease - Simplify your life with our ToDo!</h1><img class="rezed" src="{% static 'todo/assets/img/bubble-gum-verification.gif'%}" style="position: relative;margin-right: 0px;">
            </div>
            <div class="col-md-6 col-lg-6" style="padding: 40px;width: 60%;background: white;border-top-left-radius: 0px;border-bottom-left-radius: 0px;position: relative;height: 100%;margin-left: -10%;">
                <div class="text-sm-end d-lg-flex ml-auto rightposned" style="position: absolute;">
                    <div class="dropdown"><button class="btn btn-primary dropdown-toggle btntranslate" aria-expanded="false" data-bs-toggle="dropdown" type="button">ENGLISH(UK)&nbsp;</button>
                        <div class="dropdown-menu"><a class="dropdown-item" href="#">First Item</a><a class="dropdown-item" href="#">Second Item</a><a class="dropdown-item" href="#">Third Item</a></div>
                    </div>
                </div>
                <div style="margin-top: 50px;width: 70%;margin-right: 0px;margin-left: 30px;position: absolute;" class="extended">
                    <h2 style="font-size: 25px;font-family: Poppins, sans-serif;font-weight: bold;text-align: left;margin-bottom: 30px;">Sign in</h2>
                    <div class="spaced">
                        <div class="d-lg-flex justify-content-lg-center align-items-lg-center signed" style="width: 190px;height: 45px;border-radius: 9px;border-top-left-radius: 9px;text-align: center;padding-left: 0px;margin-left: 0px;"><img src="{% static 'todo/assets/img/search%201.png'%}" style="height: 25px;">
                            <p style="margin-bottom: 0px;margin-left: 10px;font-size: 12px;">Sign up with Google </p>
                        </div>
                        <div class="d-lg-flex justify-content-lg-center align-items-lg-center signed" style="display: flex;width: 190px;height: 45px;border-radius: 9px;border-top-left-radius: 9px;padding-left: 0px;text-align: center;border-top-right-radius: 9p;"><img src="{% static 'todo/assets/img/facebook%201.png'%}" style="height: 25px;">
                            <p style="margin-bottom: 0px;margin-left: 10px;font-size: 12px;">Sign up with facebook</p>
                        </div>
                    </div>
                    <h1 style="font-size: 18px;font-family: Poppins, sans-serif;text-align: center;margin-top: 40px;color: #909090;margin-bottom: 30px;">-OR-</h1>
                    <div class="formed">
                            <form class="signup-form"method="POST">
                            {% csrf_token %}
                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label class="label" for="username">Username</label>
                                                        {{ form.username }}
                                                    </div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">
                                                        <label class="label" for="password">Password</label>
                                                        {{ form.password }}
                                                    </div>
                                                </div>
                                                
                                            </div>
                            <div class="col-md-12">
                                <div class="form-group">
                                    <button type="submit" class="btn btn-primary">Sign In</button>
                                </div>
                            </div>
                            </form>
                            <div class="w-100">
                                <p class="mt-4">Don't have an account? <a href="{% url 'to_do_list:signup' %}">Register</a></p>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% include 'base/js.html' %}
</body>

</html>

to_do_list/templates/to_do_list/signup2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>to-do</title>
    <link rel="stylesheet" href="{% static 'todo/assets/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Muli&amp;display=swap">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins&amp;display=swap">
    <link rel="stylesheet" href="{% static 'todo/assets/fonts/fontawesome-all.min.css'%}">
    <link rel="stylesheet" href="{% static 'todo/assets/css/Login-Form-Basic-icons.css'%}">
    <link rel="stylesheet" href="{% static 'todo/assets/css/untitled.css'%}">
</head>

<body style="max-width: 100vw;max-height: 100vh;height: 100vh;overflow: hidden;overflow-y: hidden;">
    <section style="width: 100%;height: 100%;padding: 0px;" class="signup">
        <div class="row" style="width: 100%;height: 100%;background: white;margin: 0px;">
            <div class="col-md-6" style="padding: 40px;background: #47126B;width: 50%;height: 100%;">
                <div style="background: white;width: auto;height: auto;padding: 6px;text-align: center;display: inline-block;"><i class="fas fa-user-lock" style="width: 100%;font-size: 28px;"></i></div>
                <h1 style="color: white;font-size: 22px;font-family: Poppins, sans-serif;margin-top: 30px;width: 80%;">Get more done with ease - Simplify your life with our ToDo!</h1><img class="rezed" src="{% static 'todo/assets/img/Abstraction.png'%}" style="position: relative;">
            </div>
            <div class="col-md-6 col-lg-6" style="padding: 40px;width: 60%;background: white;border-top-left-radius: 0px;border-bottom-left-radius: 0px;position: relative;height: 100%;margin-left: -10%;">
                <div class="text-sm-end d-lg-flex ml-auto rightposned" style="position: absolute;">
                    <div class="dropdown"><button class="btn btn-primary dropdown-toggle btntranslate" aria-expanded="false" data-bs-toggle="dropdown" type="button">ENGLISH(UK)&nbsp;</button>
                        <div class="dropdown-menu"><a class="dropdown-item" href="#">First Item</a><a class="dropdown-item" href="#">Second Item</a><a class="dropdown-item" href="#">Third Item</a></div>
                    </div>
                </div>
                <div style="margin-top: 50px;width: 70%;margin-right: 0px;margin-left: 30px;position: absolute;" class="extended">
                    <h2 style="font-size: 25px;font-family: Poppins, sans-serif;font-weight: bold;text-align: left;margin-bottom: 30px;">Create Account</h2>
                    <div class="spaced">
                        <div class="d-lg-flex justify-content-lg-center align-items-lg-center signed" style="width: 190px;height: 45px;border-radius: 9px;border-top-left-radius: 9px;text-align: center;padding-left: 0px;margin-left: 0px;"><img src="{% static 'todo/assets/img/search%201.png'%}" style="height: 25px;">
                            <p style="margin-bottom: 0px;margin-left: 10px;font-size: 12px;">Sign up with Google </p>
                        </div>
                        <div class="d-lg-flex justify-content-lg-center align-items-lg-center signed" style="display: flex;width: 190px;height: 45px;border-radius: 9px;border-top-left-radius: 9px;padding-left: 0px;text-align: center;border-top-right-radius: 9p;"><img src="{% static 'todo/assets/img/facebook%201.png'%}" style="height: 25px;">
                            <p style="margin-bottom: 0px;margin-left: 10px;font-size: 12px;">Sign up with facebook</p>
                        </div>
                    </div>
                    <h1 style="font-size: 18px;font-family: Poppins, sans-serif;text-align: center;margin-top: 40px;color: #909090;margin-bottom: 30px;">-OR-</h1>
                     <div class="formed">
              
                            
                            
                        
                     
                    
                        <form method="POST">
                            {% csrf_token %}
                            <p>{{form.errors}}</p>
                            <p>
                            <label>{{form.username.label}}</label>
                            {{form.username}}
                            </p>
                            <p>
                            <label>{{form.email.label}}</label>
                            {{form.email}}
                            </p>
                            <p>
                            <label>{{form.password1.label}}</label>
                            {{form.password1}}
                            </p>
                            <p>
                            <label>{{form.password2.label}}</label>
                            {{form.password2}}
                            </p>
                            <input style="margin-top:10px ;" class="button" type="submit" value="Register">
                        </form><p>Already have an account? <a href="{% url 'to_do_list:signin'%}">Login</a></p>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'todo/assets/bootstrap/js/bootstrap.min.js'%}"></script>
    <script src="{% static 'todo/assets/js/new-age.js'%}"></script>
</body>

</html>

to_do_list/templates/to_do_list/task.html
{% extends 'to_do_list/main.html' %}
{% block content %}

<h1>Task: {{task}}
    
 {% endblock content %}

to_do_list/templates/to_do_list/task_confirm_delete.html
{% extends 'to_do_list/main.html' %}
{% block content %}

<a href="{% url 'to_do_list:tasks' %}">Go back</a>
<form method="POST">
     {% csrf_token %} 
     <p>Are you Sure you want to delete this task?"{{task}}"</p>
     <input type="submit" value="Delete"/>
</form>

{% endblock content %}

to_do_list/templates/to_do_list/task_form.html
{% extends 'to_do_list/main.html' %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/jquery-ui.min.css" integrity="sha256-/8xGgcV6Mp9fFa2u2lLYOWYNluCdrHEvBfiwhpkD/Js=" crossorigin="anonymous" />


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/south-street/theme.min.css" integrity="sha256-j5WK5GB3+w3i2jRf0bV9dkjJ+mm+TiSEG6WgNiD+gWk=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.structure.min.css" integrity="sha256-rxais37anKUnpL5QzSYte+JnIsmkGmLG+ZhKSkZkwVM=" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/dmuy/MDTimePicker.min/dist/mdtimepicker.js/mdtimepicker.css">

<h3>Create Task</h3>

<form method="POST" action="{% url 'to_do_list:task-create' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" id="title" name="title">
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        <textarea class="form-control" id="description" name="description"></textarea>
    </div>
    <div class="form-group">
        <label for="due">Due date:</label>
        <input type="text" class="form-control" id="due" name="due">
    </div>
    <div class="form-group">
        <label for="time">Reminder time:</label>
        <input type="text"  id="timepicker" name="time">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

<script
  src="https://code.jquery.com/jquery-3.5.0.min.js"
  integrity="sha256-xNzN2a4ltkB44Mc/Jz3pT4iU1cmeR0FkXs4pru/JxaQ="
  crossorigin="anonymous">
</script>
<script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
  crossorigin="anonymous">
</script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/dmuy/MDTimePicker.min/dist/mdtimepicker.js/mdtimepicker.min.js"></script>
<script>
    
$(document).ready(function() {
    $('#due').datepicker({
        dateFormat: 'yy-mm-dd'
    });
    $('.mdtimepicker').mdtimepicker({
        timeFormat: 'hh:mm',
        theme: 'purple'
    });
});

</script>
{% endblock content %}

to_do_list/templates/to_do_list/task_list.html
{% extends 'to_do_list/main.html' %}
{% block content %}

{% if request.user.is_authenticated %}
<div class="row" style= "width = 100% ">
  <div class="col-lg-6 mb-4"   >
    <div class="card shadow mb-4"></div>
    <div class="card shadow mb-4" style= "width = 100% " >
      <div class="card-header py-3">
        <h6 style="color: #27104e; font-weight: bold">
          Todo List
        </h6>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          
          <div class="row align-items-center no-gutters "data-position="{{task.pk}}" >
            {% for task in tasks %}
            <div class="col me-2">
              <a href="{% url 'to_do_list:task-update' task.id %}">
              <h6 class="mb-0"><strong>{{task}}</strong></h6></a> 
              
              <span style="float: right;" class="timer"><b >{{ task.due|timeuntil }}</b> </span>
            </div>""
            <div class="col-auto">
                           <div class="form-check">
                <input
                  class="form-check-input"
                  type="checkbox"
                  id="formCheck-1"
                /><label
                  class="form-check-label"
                  for="formCheck-1"
                ></label>
              
              </div>
              <div class="task-controls">
                <a class="delete-link"  href="{% url 'to_do_list:task-delete' task.id %}"><i class="far fa-trash-alt"></i></a>
                                <span class="handle">&nbsp;&#10247;</span>
            </div>
            </div>
            {% endfor %}
          </div>
          
        </li>
        {% endif %}
        
      </ul>
    </div>
  </div>
</div>

</div>
<div><img /></div>
</div>



{% endblock content %}